# dfc-providerportal-tribalimporter

trigger:
- master

pool:
  name: 'Continuous Deployment - HDD - 250ACU'

steps:
- task: BuildSSIS@1
  inputs:
    solnPath: 'TribalToNCS-Importer.sln'
    solnConfigName: 'Development'
    projPath: '/src/TribalToNCS-Importer/TribalToNCS-Importer.dtproj'
    projConfigName: 'Development'
    cmdSwitch: 'build'
    devenvVersion: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe'
  displayName: 'BuildSSIS - tribalimporter'

- task: CopyFiles@2
  inputs:
    Contents: '**\*.ispac'
    TargetFolder: '$(BuildArtifactStagingDirectory)'
  displayName: 'CopyFiles to '
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'