# dfc-providerportal-tribalimporter

trigger:
- master
- dev

pool:
  name: 'NCS - CI and CD'

steps:
- task: BuildSSIS@1
  inputs:
    solnPath: 'TribalToNCS-Importer.sln'
    solnConfigName: 'Development'
    projPath: 'src/TribalToNCS-Importer/TribalToNCS-Importer.dtproj'
    projConfigName: 'Development'
    cmdSwitch: 'build'
    devenvVersion: 'custom'
    denevPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Devenv.com'
  displayName: 'BuildSSIS - tribalimporter'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.BuildDirectory)
    Contents: '**\*.ispac'
    TargetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'CopyFiles to Build.ArtifactStagingDirectory'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
    publishLocation: 'Container'

